### ISSUE TITLE
Fix the test taking the unregistered dependence Mitosis into account.

### ISSUE THREAD

**Issue by mschauer** [mschauer/MitosisStochasticDiffEq.jl#2]
Perhaps @mmider knows how to fix this?

**Comment by mmider** [comment]
I can't remember if I ever used an unregistered dependence at test-time.

But I dealt with related problems.
- If the package has an unregistered dependence, then it is enough to push the `Manifest` file that contains an entry with an unregistered dependence that specifies the github address of that package (and not the local address on your computer; this gets a little fiddly quite quickly...), see for instance: https://github.com/JuliaDiffusionBayes/ExtensibleMCMCPlots.jl/blob/master/Manifest.toml#L77-L83 (package ExtensibleMCMCPlots.jl depends on ExtensibleMCMC.jl, neither of which is registered).
- If you want to build documentation for a package that depends on an unregistered package, then you need to update the `.travis.yml` file by running a short julia script that downloads the unregistered dependency from github, see: https://github.com/JuliaDiffusionBayes/ExtensibleMCMCPlots.jl/blob/master/.travis.yml#L19.

Perhaps it is possible to write an analogous script to the second case above, but instead of having it executed at the stage of building the documentation https://github.com/JuliaDiffusionBayes/ExtensibleMCMCPlots.jl/blob/master/.travis.yml#L15, have it called prior to running the tests.

**Comment by mschauer** [comment]
Thank you, that helps!
